apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: situ-space-tls
spec:
  secretName: situ-space
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: situ.space
  dnsNames:
    - situ.space
    - www.situ.space
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - situ.space
          - www.situ.space
