apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-multi-com-tls
spec:
  secretName: situ-space
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: situ.space
  dnsNames:
    - situ.space
    - www.situ.space
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - situ.space
          - www.situ.space
